### PR TITLE
[Do Not Merge][In Progress] IPTC Metadata Extraction of Priority 1 fields

### PR DESCRIPTION
**Pull request by imjalpreet**
@oparoz I have written the code for extracting priority 1 data fields from IPTC metadata. But as we know there is no GPS Longitude and Latitude in IPTC, I have right now extracted the city, state and country fields from the metadata.

Please review.

### CODE REVIEW

**Comment by oparoz** [comment]
One thing we will need to do is find a way to convert a location to GPS coordinates if we can. To do it offline probably requires using a 3rd party lib such as GeoIP.
Could you investigate?

**Comment by imjalpreet** [comment]
@oparoz Okay, I will look into it

**Comment by imjalpreet** [comment]
@oparoz I have tried to do it and I am successful but the problem is my method is online and I haven't found a way to do it offline yet. Do you have any method in mind?

**Comment by imjalpreet** [comment]
@oparoz The method that I am using uses the Google API, so it cannot be done offline.

**Comment by imjalpreet** [comment]
PR has been shifted to #34

**Pull request closed without merging**
