### PR TITLE
Minor changes to ImageDimension Class

### PR DESCRIPTION
**Pull request by imjalpreet**
I have removed the JsonSerialize method for now.

Reviewer: @oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
So, you've tested the code and everything still works without it? Info is logged and data stored in the DB?
Maybe this was for your `find` command to retrieve the info?

**Comment by imjalpreet** [comment]
@oparoz Yes, I had tested the code and everything worked. 
But I didn't get your find command reference.

**Comment by oparoz** [comment]
I was thinking about this `find` command which retrieves the data:
https://github.com/interfasys/mediametadata/blob/master/lib/Services/ImageDimensionMapper.php#L30

**Comment by imjalpreet** [comment]
@oparoz Yes, the find command is also not being used right now but I had written it to test whether the I am able to retrieve the data, which I have to in the future,

**Comment by oparoz** [comment]
OK, but then it shouldn't be a problem to keep these methods in.

**Comment by imjalpreet** [comment]
@oparoz Do you want to keep both the methods?

**Comment by oparoz** [comment]
If it's only testing code you won't use again, then you can remove them, but if they're going to be used later, then you can just leave them.

**Comment by imjalpreet** [comment]
I wasn't sure for json serialize, that's why I decided to remove it. But I think find may be useful in the future, that's why I think we can keep it.

**Comment by oparoz** [comment]
Then let's close this PR for now.

**Pull request closed without merging**
