### PR TITLE
Basic test setup

### PR DESCRIPTION
**Pull request by imjalpreet**
@oparoz I have split #21 into two PRs. This PR does not contain the ImageHooksTest as requested by you.

### CODE REVIEW

**Comment by oparoz** [comment]
Coverage tests fail with `PHP Fatal error:  Uncaught Error: Class 'PHP_CodeCoverage'`.
Could you investigate why this is happening?
Maybe a simple composer update will fix the problem. I saw that there was a new c3 component released recently.

**Comment by imjalpreet** [comment]
@oparoz Could you tell when did you get this error? I will try to test it on my machine.

**Comment by oparoz** [comment]
Sure, look at the report from Travis CI

**Comment by oparoz** [comment]
Since we need to get moving, here is what needs to be changed:
- Use newer require-dev for your composer.json, you copied the one from an older version of Gallery: https://github.com/owncloud/gallery/blob/master/composer.json
- Disable code-coverage for now and we'll enable it once we have tests running

**Comment by imjalpreet** [comment]
@oparoz Can you please check if changes are correct? I think I have disabled the code coverage for now and also updated the versions.

**Comment by oparoz** [comment]
If you look at the Travis report, you'll notice that you're not running the test: PHP7 + mysql, so just create a new line below the commented one with the same content except the extra coverage flags and we should be good to go.

**Comment by imjalpreet** [comment]
Done.

**Comment by oparoz** [comment]
Thanks!

**Pull request merged**
