### PR TITLE
Issue #16: Added code for extraction of EXIF Data

### PR DESCRIPTION
**Pull request by imjalpreet**
@oparoz I have added the extraction of EXIF Data. I will soon push the code for IPTC and XMP data as well after this gets merged.

### CODE REVIEW

**Comment by oparoz** [comment]
I think it would have been best to do it one field at a time. but no need to remove anything.

Add a unit test for date added, based on your previous work with Entity.

**Comment by imjalpreet** [comment]
@oparoz I am writing the test but I wanted to confirm one thing that in this test I have to test the Services(ExtractMetadata and StoreMetadata), right? or am I doing something wrong?

**Comment by oparoz** [comment]
As a general rule, all public methods have to be tested, so in this case, we're talking about the Services, including ImageDimension.

**Comment by oparoz** [comment]
Just add the tests one at a time until they all pass, but always thing about the various "paths", just like with ImageHooks. We don't just test when the method returns the expected result, but also when something goes wrong to make sure we catch these cases too.

**Comment by imjalpreet** [comment]
@oparoz I have added the tests for ExtractMetadata Service and StoreMetadata Service. I have made the StoreMetadata Service to work by overriding the ImageDimension service in the test but I am not able pass the extractMetadata test. Can you please check if both of them are correct?

**Comment by imjalpreet** [comment]
@oparoz After this test gets passed I think we can complete the extraction of all the three types quickly as I have already written the code and only tests will have to be added which will be just some addition to this code. I am trying to make it pass but if you have any suggestion, it would be helpful.

**Pull request merged**
