### PR TITLE
#5 Database Fields updated

### PR DESCRIPTION
**Pull request by imjalpreet**
@oparoz I have updated the database.xml file. Please check if everything is correct. I have tested it.

### CODE REVIEW

**Comment by oparoz** [comment]
Just a heads up, in the first version, we'll go with priority 1 items only and once we have extractors and writers, we'll be able to quickly add priority 2 items.

**Comment by imjalpreet** [comment]
@oparoz I will update it then.

**Comment by oparoz** [comment]
I think the name of the index should be changed

**Comment by imjalpreet** [comment]
@oparoz Okay, I will change it. Do you have any suggestions? I mean are there any rules to be followed while naming it?

**Comment by oparoz** [comment]
There are a few conventions, but what bothers me in the current version is that `image_size` is not meaningful.

Something like `idx_id` per example would be pretty explicit: Index for for field `id`.

**Comment by imjalpreet** [comment]
Done.

**Comment by oparoz** [comment]
Thanks!

**Comment by imjalpreet** [comment]
@oparoz Do you want anymore changes in this?

**Comment by oparoz** [comment]
Could you just rebase it?

**Comment by imjalpreet** [comment]
@oparoz I rebased it.

**Comment by oparoz** [comment]
Thank you :)

**Pull request merged**
